/* 
 * This file declares column numbers found in hlist and tree files. 
 */ 

#ifndef COLUMNS_H 
#define COLUMNS_H 

#define SCALE_COLUMN 0 
#define ID_COLUMN 1 
#define DESC_SCALE_COLUMN 2 
#define DESC_ID_COLUMN 3 
#define NUM_PROG_COLUMN 4 
#define PID_COLUMN 5 
#define UPID_COLUMN 6 
#define DESC_PID_COLUMN 7 
#define PHANTOM_COLUMN 8 
#define SAM_MVIR_COLUMN 9 
#define MVIR_COLUMN 10 
#define RVIR_COLUMN 11 
#define RS_COLUMN 12 
#define VRMS_COLUMN 13 
#define MMP_COLUMN 14 
#define SCALE_OF_LAST_MM_COLUMN 15 
#define VMAX_COLUMN 16 
#define X_COLUMN 17 
#define Y_COLUMN 18 
#define Z_COLUMN 19 
#define VX_COLUMN 20 
#define VY_COLUMN 21 
#define VZ_COLUMN 22 
#define JX_COLUMN 23 
#define JY_COLUMN 24 
#define JZ_COLUMN 25 
#define SPIN_COLUMN 26 
#define BREADTH_FIRST_ID_COLUMN 27 
#define DEPTH_FIRST_ID_COLUMN 28 
#define TREE_ROOT_ID_COLUMN 29 
#define ORIG_HALO_ID_COLUMN 30 
#define SNAP_NUM_COLUMN 31 
#define NEXT_COPROGENITOR_DEPTHFIRST_ID_COLUMN 32 
#define LAST_PROGENITOR_DEPTHFIRST_ID_COLUMN 33 
#define LAST_MAINLEAF_DEPTHFIRST_ID_COLUMN 34 
#define TIDAL_FORCE_COLUMN 35 
#define TIDAL_ID_COLUMN 36 
#define RS_KLYPIN_COLUMN 37 
#define MMVIR_ALL_COLUMN 38 
#define M200B_COLUMN 39 
#define M200C_COLUMN 40 
#define M500C_COLUMN 41 
#define M2500C_COLUMN 42 
#define XOFF_COLUMN 43 
#define VOFF_COLUMN 44 
#define SPIN_BULLOCK_COLUMN 45 
#define B_TO_A_COLUMN 46 
#define C_TO_A_COLUMN 47 
#define AX_COLUMN 48 
#define AY_COLUMN 49 
#define AZ_COLUMN 50 
#define B_TO_A500C_COLUMN 51 
#define C_TO_A500C_COLUMN 52 
#define AX500C_COLUMN 53 
#define AY500C_COLUMN 54 
#define AZ500C_COLUMN 55 
#define T_OVER_U_COLUMN 56 
#define M_PE_BEHROOZI_COLUMN 57 
#define M_PE_DIEMER_COLUMN 58 
#define MACC_COLUMN 59 
#define MPEAK_COLUMN 60 
#define VACC_COLUMN 61 
#define VPEAK_COLUMN 62 
#define HALFMASS_SCALE_COLUMN 63 
#define ACC_RATE_INST_COLUMN 64 
#define ACC_RATE_100MYR_COLUMN 65 
#define ACC_RATE_1TDYN_COLUMN 66 
#define ACC_RATE_2TDYN_COLUMN 67 
#define ACC_RATE_MPEAK_COLUMN 68 
#define MPEAK_SCALE_COLUMN 69 
#define ACC_SCALE_COLUMN 70 
#define FIRST_ACC_SCALE_COLUMN 71 
#define FIRST_ACC_MVIR_COLUMN 72 
#define FIRST_ACC_VMAX_COLUMN 73 
#define VMAX_AT_MPEAK_COLUMN 74 
#define TIDAL_FORCE_TDYN_COLUMN 75 
#define LOG_VMAX_OVER_MAXVMAX_COLUMN 76 
#define TIME_TO_FUTURE_MERGER_COLUMN 77 
#define FUTURE_MERGER_MMP_ID 78 

#endif /* COLUMNS_H */ 

